+incdir+../SystemVerilog/Design
+incdir+tb
+incdir+tb/interfaces
+incdir+tb/agents/uart
+incdir+tb/pkg
+incdir+tb/monitors
+incdir+tb/ref
+incdir+tb/scoreboard
+incdir+tb/coverage
+incdir+tb/sequences
+incdir+tb/env
+incdir+tb/tests

../SystemVerilog/Design/common.sv
../SystemVerilog/Design/alu.sv
../SystemVerilog/Design/control.sv
../SystemVerilog/Design/register_file.sv
../SystemVerilog/Design/instr_decompressor.sv
../SystemVerilog/Design/fetch_stage.sv
../SystemVerilog/Design/decode_stage.sv
../SystemVerilog/Design/execute_stage.sv
../SystemVerilog/Design/data_memory.sv
../SystemVerilog/Design/program_memory.sv
../SystemVerilog/Design/mem_stage.sv
../SystemVerilog/Design/forwarding_unit.sv
../SystemVerilog/Design/stall_unit.sv
../SystemVerilog/Design/gshare_predictor.sv
../SystemVerilog/Design/uart.sv
../SystemVerilog/Design/uart_wrapper.sv
../SystemVerilog/Design/cpu.sv

tb/interfaces/uart_if.sv
tb/interfaces/cpu_mon_if.sv
tb/agents/uart/uart_pkg.sv
tb/cpu_mon_bind.sv
tb/cpu_tb_pkg.sv
tb/cpu_tb_top.sv
